### ISSUE TITLE
FEATURE REQUEST: Add num filter to links

### ISSUE THREAD

**Issue by Ch3LL** [cbodden/irc-bashbot#1]
I want to be able to run `.links show 5` so i can filter the amount of links that are displayed.

**Comment by cbodden** [comment]
cool. looking into that now. should have a status in a bit.

**Comment by cbodden** [comment]
aight - all tested and added in commits:
6added425c91ade49926000980481d9934aa671f
7aa08c8cd3af89ea9e9cc429c4f297f357f65e8f
dcca979396aed55857bf0c509b225d494da8acc9
006868607de3e76c3a5d7fa84c713c3fc5a1f207
